import { BLUE_GRIMLY } from "src/styles/colors";

export const initDataConfig = {
  graphTitle: "Disease Reduction by Species",
  graphBackgroundColor: BLUE_GRIMLY,
  graphData: [
    {
      id: "pronghorn",
      label: "Pronghorn",
      dataSets: "12",
      sampleSize: "2,015",
      barOne: "54%",
      barTwo: "72%",
      barThree: "76%",
      barFour: "60%",
    },
    {
      id: "elk",
      label: "Elk",
      dataSets: "5",
      sampleSize: "894",
      barOne: "50%",
      barTwo: "71%",
      barThree: "76%",
      barFour: "54%",
    },
    {
      id: "bighorn",
      label: "Bighorn",
      dataSets: "14",
      sampleSize: "3,886",
      barOne: "53%",
      barTwo: "69%",
      barThree: "74%",
      barFour: "59%",
    },
    {
      id: "moose",
      label: "Moose",
      dataSets: "7",
      sampleSize: "1,205",
      barOne: "54%",
      barTwo: "79%",
      barThree: "82%",
      barFour: "63%",
    },
    {
      id: "caribou",
      label: "Caribou",
      dataSets: "11",
      sampleSize: "1,944",
      barOne: "53%",
      barTwo: "73%",
      barThree: "77%",
      barFour: "63%",
    },
  ],
};
