export const dataConfig = [
  {
    id: "manufacturing",
    label: "Manufacturing",
    clients: "131",
    members: "2.3M+",
    pain: "54%",
    depression: "72%",
    anxiety: "76%",
    surgery: "60%",
  },
  {
    id: "retail",
    label: "Retail",
    clients: "27",
    members: "660,000+",
    pain: "50%",
    depression: "71%",
    anxiety: "76%",
    surgery: "54%",
  },
  {
    id: "professional",
    label: "Professional Services",
    clients: "140",
    members: "2.3M+",
    pain: "53%",
    depression: "69%",
    anxiety: "74%",
    surgery: "59%",
  },
  {
    id: "public",
    label: "Public Sector",
    clients: "21",
    members: "600,000+",
    pain: "54%",
    depression: "79%",
    anxiety: "82%",
    surgery: "63%",
  },
  {
    id: "cpg",
    label: "CPG",
    clients: "24",
    members: "800,000+",
    pain: "53%",
    depression: "73%",
    anxiety: "77%",
    surgery: "63%",
  },
];
