import { BLUE_GRIMLY } from "src/styles/colors";

export const initDataConfig = {
  graphTitle: "Disease Reduction by Species",
  graphBackgroundColor: BLUE_GRIMLY,
  graphData: [
    {
      id: "lowar",
      label: "Lowar",
      dataSets: "25",
      sampleSize: "2.3M",
      barOne: "54%",
      barTwo: "72%",
      barThree: "76%",
      barFour: "60%",
    },
    {
      id: "Amards",
      label: "Amards",
      dataSets: "20",
      sampleSize: "660,000",
      barOne: "50%",
      barTwo: "71%",
      barThree: "76%",
      barFour: "54%",
    },
    {
      id: "decent",
      label: "Decent",
      dataSets: "14",
      sampleSize: "2.3M",
      barOne: "53%",
      barTwo: "69%",
      barThree: "74%",
      barFour: "59%",
    },
    {
      id: "uppar",
      label: "Uppar",
      dataSets: "21",
      sampleSize: "600,000",
      barOne: "54%",
      barTwo: "79%",
      barThree: "82%",
      barFour: "63%",
    },
    {
      id: "control",
      label: "Control",
      dataSets: "24",
      sampleSize: "800,000",
      barOne: "53%",
      barTwo: "73%",
      barThree: "77%",
      barFour: "63%",
    },
  ],
};
